# This is a basic workflow to help you get started with Actions

name: Upload scripts on release

on: release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Upload auth.py
      uses: JasonEtco/upload-to-release@master
      with:
        args: auth.py application/x-python
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload backup.py
      uses: JasonEtco/upload-to-release@master
      with:
        args: backup.py application/x-python
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
